// <auto-generated />
using System;
using FotbollTournament.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FotbollTournament.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FotbollTournament.Model.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            AwayScore = 1,
                            AwayTeamId = 2,
                            GameDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeScore = 2,
                            HomeTeamId = 1,
                            TournamentId = 1
                        },
                        new
                        {
                            GameId = 2,
                            AwayScore = 3,
                            AwayTeamId = 4,
                            GameDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeScore = 0,
                            HomeTeamId = 3,
                            TournamentId = 1
                        });
                });

            modelBuilder.Entity("FotbollTournament.Model.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            FirstName = "Adam",
                            LastName = "Karlsson",
                            Position = "Forward",
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 2,
                            FirstName = "Leo",
                            LastName = "Nilsson",
                            Position = "Midfielder",
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 3,
                            FirstName = "Isak",
                            LastName = "Johansson",
                            Position = "Defender",
                            TeamId = 2
                        },
                        new
                        {
                            PlayerId = 4,
                            FirstName = "Elias",
                            LastName = "Persson",
                            Position = "Goalkeeper",
                            TeamId = 2
                        },
                        new
                        {
                            PlayerId = 5,
                            FirstName = "Yusuf",
                            LastName = "Ahmed",
                            Position = "Forward",
                            TeamId = 3
                        },
                        new
                        {
                            PlayerId = 6,
                            FirstName = "Bilal",
                            LastName = "Hassan",
                            Position = "Midfielder",
                            TeamId = 3
                        },
                        new
                        {
                            PlayerId = 7,
                            FirstName = "Oscar",
                            LastName = "Lindberg",
                            Position = "Defender",
                            TeamId = 4
                        },
                        new
                        {
                            PlayerId = 8,
                            FirstName = "Viktor",
                            LastName = "Sjöberg",
                            Position = "Forward",
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("FotbollTournament.Model.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("CoachName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            CoachName = "Anders Larsson",
                            TeamName = "Göteborg FC",
                            TournamentId = 1
                        },
                        new
                        {
                            TeamId = 2,
                            CoachName = "Maria Svensson",
                            TeamName = "Hisingen United",
                            TournamentId = 1
                        },
                        new
                        {
                            TeamId = 3,
                            CoachName = "Omar Ali",
                            TeamName = "Angered Stars",
                            TournamentId = 1
                        },
                        new
                        {
                            TeamId = 4,
                            CoachName = "Johan Berg",
                            TeamName = "Frölunda IF",
                            TournamentId = 1
                        });
                });

            modelBuilder.Entity("FotbollTournament.Model.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            TournamentId = 1,
                            EndDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Göteborg Cup 2025",
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FotbollTournament.Model.Game", b =>
                {
                    b.HasOne("FotbollTournament.Model.Team", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FotbollTournament.Model.Team", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FotbollTournament.Model.Tournament", "Tournament")
                        .WithMany("Games")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FotbollTournament.Model.Player", b =>
                {
                    b.HasOne("FotbollTournament.Model.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FotbollTournament.Model.Team", b =>
                {
                    b.HasOne("FotbollTournament.Model.Tournament", "Tournament")
                        .WithMany("Teams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FotbollTournament.Model.Team", b =>
                {
                    b.Navigation("AwayGames");

                    b.Navigation("HomeGames");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("FotbollTournament.Model.Tournament", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
